/**
 * A curated opening repertoire for training.
 *
 * Hand-written rather than pulled from a database: the point is not coverage but
 * the *ideas*, so every line carries why the moves are played, what the
 * middlegame looks like, and the mistake people actually make. Lines run about
 * ten moves a side — far enough that the middlegame plan is already visible on
 * the board when the theory stops.
 */
export type Opening = {
  id: string;
  name: string;
  eco: string;
  /** The side whose repertoire this is — the side you practise. */
  side: 'w' | 'b';
  family: string;
  /** Main line in SAN, from the starting position. */
  moves: string[];
  /** What the opening is trying to achieve, in one or two sentences. */
  idea: string;
  /** Notes on individual moves, keyed by ply index (0 = the first move). */
  notes: Record<number, string>;
  /** Typical middlegame plans once the opening is done. */
  plans: string[];
  /** The mistake that actually costs people games here. */
  watchOut: string;
};

export const OPENINGS: Opening[] = [
  /* ---------------- 1.e4 e5 ---------------- */
  {
    id: 'italian',
    name: 'Italian Game, Giuoco Pianissimo',
    eco: 'C50',
    side: 'w',
    family: '1.e4 e5',
    moves: [
      'e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'c3', 'Nf6', 'd3', 'd6',
      'O-O', 'O-O', 'Re1', 'a6', 'Nbd2', 'Ba7', 'h3', 'Ne7', 'Nf1', 'Ng6',
    ],
    idea: 'The most natural opening in chess: occupy the centre, develop toward it, castle. The bishop on c4 eyes f7, the weakest square in Black’s camp before castling, and the slow d3/c3 build-up keeps every piece on a good square while White prepares d4.',
    notes: {
      4: 'Bc4 takes aim at f7. Only the king defends it, which is why so many early attacks land there.',
      6: 'c3 prepares d4 — the pawn duo on d4 and e4 is what White is really after.',
      8: 'd3 is the modern, patient choice: hold the centre, finish developing, push d4 later on your own terms.',
      12: 'Re1 backs up e4 so the knight on f3 is free to move later without dropping a pawn.',
      13: 'a6 is useful for Black too: it takes b5 away and prepares ...Ba7 so the bishop is never hit by d4.',
      14: 'Nbd2 heads for f1 and g3. The knight is doing nothing on d2 for exactly two moves, and everything afterwards.',
      16: 'h3 stops ...Bg4 pinning the f3 knight, which matters the moment you commit to d4.',
      18: 'Nf1 is the Italian regrouping in miniature — d2 to f1 to g3 or e3, both of them better squares.',
    },
    plans: [
      'Play d4 when it gains time or opens lines, not automatically — the tension helps you.',
      'Re1, Nbd2, Nf1, Ng3 is the classic regrouping: the knight joins the kingside attack.',
      'Keep the light-squared bishop; retreat it to b3 rather than trade it for a knight.',
      'If Black locks the centre with ...d5 and ...d4, switch wings: a4 and b4 to open lines where you have space.',
      'Ne3 and Nf5 is the other knight route — an outpost on f5 is worth several tempi of manoeuvring.',
      'Once the knight reaches g3, Nh5 and Qf3 create a real attack against a kingside that has not been reinforced.',
    ],
    watchOut: 'Do not grab material early with Ng5 and Nxf7 ideas unless the tactics genuinely work — the attack evaporates and you are left with a misplaced knight.',
  },
  {
    id: 'ruy-lopez',
    name: 'Ruy Lopez, Closed (Chigorin)',
    eco: 'C88',
    side: 'w',
    family: '1.e4 e5',
    moves: [
      'e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7',
      'Re1', 'b5', 'Bb3', 'd6', 'c3', 'O-O', 'h3', 'Na5', 'Bc2', 'c5',
    ],
    idea: 'Pressure the knight that defends e5, then build the ideal centre behind it. The most respected opening in chess: White gets a lasting, slow initiative and a position where every piece has a known best square.',
    notes: {
      4: 'Bb5 attacks the defender of e5 rather than e5 itself — indirect pressure is the whole point.',
      5: 'a6 asks the bishop to commit. This is the Morphy Defence, played in the overwhelming majority of games.',
      10: 'Re1 defends e4 and prepares to meet ...b5 and ...Na5 calmly.',
      14: 'c3 supports d4. White has spent the opening preparing one pawn push.',
      16: 'h3 looks slow and is not: without it ...Bg4 pins the knight and d4 is permanently awkward.',
      17: 'Na5 hits the bishop. Black is willing to put the knight on the rim to remove White’s best piece.',
      18: 'Bc2 keeps the bishop and re-aims it at h7 — the b1–h7 diagonal is where the attack eventually comes from.',
      19: 'c5 stakes out the queenside and stops d4 arriving with tempo. Now the real game begins.',
    },
    plans: [
      'Nbd2–f1–g3 regrouping, then d4 with a strong centre.',
      'If Black plays ...Na5 to trade off your bishop, retreat to c2 and keep it.',
      'The d5 square and the half-open d-file are long-term targets.',
      'Close the centre with d5 when Black’s pieces are on the queenside, then attack with g4 and Nf5.',
      'Meet ...c5 with d4 and keep the tension — the c5/d6/e5 chain is hard for Black to hold if you never resolve it.',
      'a4 at the right moment cracks the b5 pawn and hands you the a-file or a weak c6 pawn.',
    ],
    watchOut: 'Bxc6 early gives up the bishop pair for very little unless you have a concrete follow-up — the Exchange Variation is a different opening with different plans.',
  },
  {
    id: 'scotch',
    name: 'Scotch Game, Classical',
    eco: 'C45',
    side: 'w',
    family: '1.e4 e5',
    moves: [
      'e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Bc5', 'Nb3', 'Bb6',
      'Nc3', 'Nf6', 'Qe2', 'd6', 'Be3', 'Bxe3', 'Qxe3', 'O-O', 'O-O-O', 'Re8',
    ],
    idea: 'Open the centre immediately instead of manoeuvring behind it. Far less theory than the Ruy Lopez, the position clarifies fast, and White gets a healthy structure plus a ready-made attacking set-up with queenside castling.',
    notes: {
      4: 'd4 strikes at once. Black must take, or concede the centre.',
      7: 'Bc5 hits the knight on d4 and takes the strong diagonal.',
      8: 'Nb3 sidesteps and gains time on the bishop.',
      12: 'Qe2 connects the rooks early and supports the plan of O-O-O rather than O-O.',
      14: 'Be3 offers the trade of Black’s best-placed piece and clears the back rank for castling long.',
      16: 'Qxe3 recaptures toward the centre — the queen on e3 covers a7, c5 and the kingside dark squares at once.',
      18: 'O-O-O commits to opposite-side play. White attacks with f4, g4 and h4; Black must be fast on the queenside.',
    },
    plans: [
      'Castle queenside and attack on the kingside with f4, g4 and h4.',
      'The half-open d-file suits a rook on d1 against Black’s d-pawn.',
      'Trade into an endgame if you win the structural battle — your pawns are healthier.',
      'f4 followed by e5 is the central break that opens lines while Black is still regrouping.',
      'Kb1 first, always: one prophylactic move is worth more than one tempo of attack in an opposite-castling race.',
      'If Black opens the b-file with ...b5–b4, answer with a central push rather than defending piece by piece.',
    ],
    watchOut: 'After 4.Nxd4, do not leave the knight sitting on d4 for Black to hit with tempo. Retreat or support it before it costs you time.',
  },
  {
    id: 'kings-gambit',
    name: 'King’s Gambit Accepted, Kieseritzky',
    eco: 'C39',
    side: 'w',
    family: '1.e4 e5',
    moves: [
      'e4', 'e5', 'f4', 'exf4', 'Nf3', 'g5', 'h4', 'g4', 'Ne5', 'Nf6',
      'd4', 'd6', 'Nd3', 'Nxe4', 'Bxf4', 'Qe7', 'Qe2', 'Bg7', 'c3', 'O-O',
    ],
    idea: 'Give up a pawn on move two to rip open the f-file and own the centre. Objectively White is not better, but the positions are wildly sharp and every tactical idea you will ever need appears in them.',
    notes: {
      2: 'f4 offers the pawn. In return White gets e4-plus-d4 in the centre and an open f-file pointing at f7.',
      5: 'g5 is the greedy, correct try: Black hangs on to the pawn and builds a chain with ...h6 to keep it.',
      6: 'h4 undermines g5 at once. Letting Black consolidate the extra pawn is how the gambit goes wrong.',
      8: 'Ne5 is the Kieseritzky move — the knight is not really hanging, because ...d6 is met by Nxg4.',
      12: 'Nd3 retreats to hold f4 and hit the loose pawn; the knight on d3 is oddly good, covering e5, f4 and b4.',
      14: 'Bxf4 finally regains the gambit pawn with a developed bishop and an open file.',
      16: 'Qe2 pins the knight on e4 along the e-file and dares Black to untangle.',
      19: 'O-O by Black is already an admission: the extra pawn is gone and both kings are safe, so this is simply a game.',
    },
    plans: [
      'Fight for the f-file: Rf1 plus a bishop on f4 is more valuable than the pawn you gave up.',
      'Build the big centre with d4 and c3 — the gambit pawn buys you space, so use it.',
      'Undermine Black’s kingside pawn chain with h4 and g3 rather than attacking it head on.',
      'Nd2xe4 or Bd3 to remove the strong knight on e4; it is Black’s only well-placed piece.',
      'If Black grabs everything and falls behind in development, open the centre immediately with e5 or d5.',
      'When the attack stalls, trade queens — White’s structure after Bxf4 is healthier than it looks.',
    ],
    watchOut: 'Do not chase the f4 pawn with pieces while your king sits on e1 and the g1–a7 diagonal is open. In the King’s Gambit, development beats material every single time.',
  },
  {
    id: 'petrov',
    name: 'Petrov (Russian) Defence',
    eco: 'C42',
    side: 'b',
    family: '1.e4 e5',
    moves: [
      'e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'd6', 'Nf3', 'Nxe4', 'd4', 'd5',
      'Bd3', 'Nc6', 'O-O', 'Be7', 'c4', 'Nb4', 'Be2', 'O-O', 'Nc3', 'Bf5',
    ],
    idea: 'Symmetry as a weapon. Black copies White instead of defending e5, aiming for a solid, low-risk position with few weaknesses and easy piece play down the e-file.',
    notes: {
      3: 'Nf6 ignores the attack on e5 and counter-attacks e4. This is the whole idea.',
      5: 'd6 first. Taking on e4 immediately loses material to Qe2, pinning the knight.',
      9: 'd5 supports the knight on e4 — without this, the knight has nowhere to live.',
      11: 'Nc6 develops and hits d4, so White can never simply build a centre for free.',
      14: 'c4 is White’s critical try: hit d5 before Black finishes developing.',
      15: 'Nb4 keeps the d5 pawn alive by attacking the bishop on d3. Tactics, not stubbornness.',
      19: 'Bf5 finishes development and reinforces the knight on e4 a second time. Black is fully equal here.',
    },
    plans: [
      'Complete development and trade pieces; the symmetrical structure favours the defender.',
      'The c-pawn break ...c5 frees the position once you are castled.',
      'Watch the e-file — rooks land there fast in this opening.',
      'Hold the knight on e4 with ...Bf5, ...Re8 and ...f5 if needed; it is the piece that makes the position comfortable.',
      'If White takes on d5, recapture with the queen and use the open files rather than clinging to symmetry.',
      'Aim for an endgame: with no pawn weaknesses, every trade takes you closer to a safe draw or a winnable rook ending.',
    ],
    watchOut: 'Never play 3...Nxe4 before ...d6. 4.Qe2 wins a piece or forces an awful position — this is the single most common way people lose the Petrov.',
  },

  /* ---------------- Sicilian ---------------- */
  {
    id: 'sicilian-najdorf',
    name: 'Sicilian, Najdorf (English Attack)',
    eco: 'B90',
    side: 'b',
    family: 'Sicilian',
    moves: [
      'e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6',
      'Be3', 'e5', 'Nb3', 'Be6', 'f3', 'Be7', 'Qd2', 'O-O', 'O-O-O', 'Nbd7',
    ],
    idea: 'The sharpest reply to 1.e4. Black trades a wing pawn for a centre pawn, takes the half-open c-file, and plays for a win rather than equality — accepting a weak d5 square in exchange for permanent activity.',
    notes: {
      1: 'c5 fights for d4 from the side, leaving the centre unbalanced from move one.',
      9: 'a6 is the Najdorf move: it stops Nb5 and Bb5 forever, and prepares ...b5 for queenside play.',
      11: 'e5 gains space and kicks the knight, at the cost of weakening d5.',
      13: 'Be6 covers d5 immediately — the square Black just weakened is the square Black must now guard.',
      14: 'f3 announces the English Attack: Qd2, O-O-O, then g4 and h4 at the black king.',
      17: 'O-O is a decision, not a formality: Black castles into the coming pawn storm and answers with speed on the other wing.',
      19: 'Nbd7 supports c5 and b6 and keeps the knight flexible. Black’s pieces are cramped but every one of them has a job.',
    },
    plans: [
      'Queenside expansion with ...b5, ...Bb7, ...Nbd7 and pressure down the c-file.',
      'The d5 square is your one structural concession — cover it with ...Be6, ...Nbd7 and sometimes ...Rc8.',
      'Against a kingside pawn storm, counter in the centre or on the queenside rather than defending passively.',
      'Count tempi before you defend: in opposite-castling positions, one move spent on ...h6 can cost the whole race.',
      'The exchange sacrifice ...Rxc3 recurs here too — it kills the attack by removing the knight that feeds it.',
      'If White ever plays a4 to stop ...b5, use the b4 square with ...Nc5 and ...Qc7 instead.',
    ],
    watchOut: 'This is the most analysed opening in chess. Do not enter sharp lines from general principles — one inaccuracy against a prepared opponent is fatal.',
  },
  {
    id: 'sicilian-dragon',
    name: 'Sicilian, Dragon (Yugoslav Attack)',
    eco: 'B78',
    side: 'b',
    family: 'Sicilian',
    moves: [
      'e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'g6',
      'Be3', 'Bg7', 'f3', 'O-O', 'Qd2', 'Nc6', 'Bc4', 'Bd7', 'O-O-O', 'Rc8',
    ],
    idea: 'Fianchetto the dark-squared bishop and aim it at the long diagonal, straight at White’s queenside. Both sides attack the enemy king; whoever is faster wins, and the margin is usually a single tempo.',
    notes: {
      9: 'g6 prepares the bishop that gives the Dragon its name and its bite.',
      11: 'Bg7 points at b2 and, once the centre opens, at White’s king.',
      12: 'f3 is White announcing the Yugoslav Attack: Qd2, O-O-O, h4-h5 and a race.',
      16: 'Bc4 is the point of the Yugoslav — it stares at f7 and, more importantly, guards d5 so ...d5 never comes.',
      17: 'Bd7 looks modest but it is the Dragon’s key move: it connects the rooks and readies ...Rc8 and ...Ne5–c4.',
      19: 'Rc8 is the Dragon in one move. The rook is aimed at c3, the square where the exchange sacrifice lands.',
    },
    plans: [
      'The exchange sacrifice ...Rxc3 is a standard resource — it wrecks White’s queenside and frees the g7 bishop.',
      'Play ...Rc8 early; the c-file is where your counterplay lives.',
      'Trade off White’s dark-squared bishop if you can — it is the main defender of the long diagonal.',
      '...Ne5 and ...Nc4 hits the bishop on e3 and gains time for the queenside attack.',
      'Meet h4–h5 with ...Nxh5 rather than ...gxh5, keeping the g-file shut in front of your king.',
      '...Qa5 and ...Rfc8 doubles on the c-file and pins the knight on c3 to the queen behind it.',
    ],
    watchOut: 'Against the Yugoslav Attack, counting tempi matters more than material. If you spend moves on anything that is not counterplay, h5 arrives first.',
  },
  {
    id: 'sicilian-accelerated-dragon',
    name: 'Sicilian, Accelerated Dragon',
    eco: 'B35',
    side: 'b',
    family: 'Sicilian',
    moves: [
      'e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'g6', 'Nc3', 'Bg7',
      'Be3', 'Nf6', 'Bc4', 'O-O', 'Bb3', 'd6', 'f3', 'Bd7', 'Qd2', 'Rc8',
    ],
    idea: 'The Dragon without spending a move on ...d6, so Black can hit the centre with ...d5 in one go. Fewer forced lines than the real Dragon and far less to memorise, with the same bishop on g7 doing the work.',
    notes: {
      7: 'g6 before ...d6 — that saved tempo is the entire point of the Accelerated Dragon.',
      11: 'Nf6 hits e4 and invites the Maróczy Bind with c4, which is the main test of the whole system.',
      12: 'Bc4 aims at f7 and, crucially, at d5 — White spends a move purely to stop ...d5.',
      15: 'd6 is played only now that ...d5 has been prevented, and it opens the c8 bishop’s diagonal.',
      17: 'Bd7 prepares ...Rc8 and keeps the option of ...Ne5 followed by ...Bc6 hitting e4.',
      19: 'Rc8 sets up the same exchange-sacrifice pressure on c3 as the classical Dragon, a move earlier.',
    },
    plans: [
      '...d5 in one move is the dream; if White prevents it, play against the c4 pawn instead.',
      'Against the Maróczy Bind (c4), manoeuvre with ...Ng4, ...Nxe3 and ...Bg7xd4 to trade off the cramping pieces.',
      '...Rc8, ...Qa5 and pressure on c3 — the same recipe as the Dragon, one tempo faster.',
      '...Ne5 and ...Bc6 builds a battery on the long diagonal that hits e4 and h1 at once.',
      'Trade a pair of knights when cramped; every trade eases a space disadvantage.',
      'If White castles queenside, race with ...b5 and ...a5 rather than trying to defend on the kingside.',
    ],
    watchOut: 'Avoid the Maróczy Bind by accident and you will be squeezed for fifty moves. If White plays c4, switch immediately from attacking plans to trading pieces.',
  },
  {
    id: 'sicilian-alapin',
    name: 'Sicilian, Alapin (2.c3)',
    eco: 'B22',
    side: 'w',
    family: 'Sicilian',
    moves: [
      'e4', 'c5', 'c3', 'Nf6', 'e5', 'Nd5', 'd4', 'cxd4', 'Nf3', 'Nc6',
      'cxd4', 'd6', 'Bc4', 'Nb6', 'Bb5', 'dxe5', 'Nxe5', 'Bd7', 'Nxd7', 'Qxd7',
    ],
    idea: 'Refuse the Open Sicilian entirely. White builds a big pawn centre with c3 and d4 and gets an easy, Ruy-Lopez-like game — no Najdorf theory, no Dragon, no memorised 25-move lines.',
    notes: {
      2: 'c3 supports d4 next move. The cost is the b1 knight’s best square; the gain is a full centre.',
      4: 'e5 kicks the knight before Black can pile on d4. A tempo now buys space for the rest of the game.',
      5: 'Nd5 is the right square — on g8 or e4 the knight would simply be chased again.',
      10: 'cxd4 gives White the classic isolated-queen-pawn centre after ...d6 and exd6, or a broad centre if Black lets it stand.',
      12: 'Bc4 hits d5 and f7 at once and asks the knight to move a second time.',
      14: 'Bb5 keeps the pin on c6 alive so that ...dxe5 can be met by Nxe5 with tempo.',
      19: 'Qxd7 leaves a symmetrical-looking position where White has the better development and a clear plan: O-O, Nc3, Re1.',
    },
    plans: [
      'Castle, put a rook on e1 or d1, and play against the d-file — the isolated d-pawn positions are pleasant for White.',
      'If the d-pawn becomes isolated, use the outpost on e5 and the free piece play rather than defending it.',
      'Bg5 and Nc3 to add pressure to d5; that square is the whole battleground.',
      'Trade a pair of minor pieces when Black is cramped — every trade helps Black, so avoid them if you have space.',
      'Push d5 at the right moment to open lines toward an uncastled or freshly castled king.',
      'Against an early ...d5 by Black, play exd6 en passant only when it damages the structure, not automatically.',
    ],
    watchOut: 'Do not autopilot 2.c3 into the Open Sicilian structures. Without a knight on c3 the d5 square belongs to Black; treat it as a d4/e4 centre game, not a Najdorf.',
  },

  /* ---------------- Other 1.e4 defences ---------------- */
  {
    id: 'french-winawer',
    name: 'French Defence, Winawer',
    eco: 'C18',
    side: 'b',
    family: 'vs 1.e4',
    moves: [
      'e4', 'e6', 'd4', 'd5', 'Nc3', 'Bb4', 'e5', 'c5', 'a3', 'Bxc3+',
      'bxc3', 'Ne7', 'Qg4', 'O-O', 'Bd3', 'Nbc6', 'Qh5', 'Ng6', 'Nf3', 'Qc7',
    ],
    idea: 'Challenge the centre immediately with ...d5 and accept a cramped but rock-solid position. Black gives up the bishop pair to wreck White’s queenside pawns and then attacks the base of the chain.',
    notes: {
      1: 'e6 prepares ...d5 with support. The cost is the light-squared bishop, which gets locked behind the pawn chain.',
      5: 'Bb4 pins the knight defending e4 — this is what makes the Winawer sharp rather than passive.',
      9: 'Bxc3+ doubles White’s pawns permanently. You give the bishop pair for a structural concession that lasts all game.',
      11: 'Ne7 rather than ...Nf6: the knight avoids e5 and heads for f5 or g6, where it hits the doubled pawns and d4.',
      12: 'Qg4 is White’s critical try, attacking g7 before Black is organised.',
      13: 'O-O calmly gives up nothing — after ...Ng6 the kingside holds, and Black gets on with the queenside attack.',
      19: 'Qc7 hits both e5 and the weak c-pawns. Every black piece now points at the same target.',
    },
    plans: [
      'Attack the base of the pawn chain with ...c5 and ...Qc7, not the head of it.',
      'The doubled c-pawns are a long-term target — pile on c3 and c4.',
      'Your light-squared bishop is the problem piece. Free it with ...b6 and ...Ba6, or trade it off.',
      '...Nf5 hits d4 and e3 and often forces White to weaken the kingside with g4.',
      'Open the a-file with ...a5 and ...a4 when White’s pieces are committed to the kingside.',
      'If White sacrifices on the kingside, count the defenders first — ...Ng6, ...Qc7 and a rook on f8 usually hold.',
    ],
    watchOut: 'Do not let the position close completely while your queenside is undeveloped. The French is cramped, and a cramped position with no counterplay is just bad.',
  },
  {
    id: 'french-advance',
    name: 'French Defence, Advance',
    eco: 'C02',
    side: 'w',
    family: 'vs 1.e4',
    moves: [
      'e4', 'e6', 'd4', 'd5', 'e5', 'c5', 'c3', 'Nc6', 'Nf3', 'Qb6',
      'a3', 'Nh6', 'b4', 'cxd4', 'cxd4', 'Nf5', 'Bb2', 'Bd7', 'Bd3', 'Rc8',
    ],
    idea: 'Answer the French by closing the centre at once. White gets space, a permanent kingside majority and a clear plan; Black’s light-squared bishop stays buried behind the pawn chain for the whole game.',
    notes: {
      4: 'e5 seizes space and shuts the c8 bishop in. This is the most direct way to punish 1...e6.',
      6: 'c3 defends d4, the base of the chain and the square Black will attack all game.',
      9: 'Qb6 is Black’s standard pressure: it hits b2 and adds a third attacker to d4.',
      10: 'a3 prepares b4, gaining space and taking c5 away from Black’s pieces for good.',
      11: 'Nh6 heads for f5, the perfect blockading square in front of the chain.',
      14: 'cxd4 keeps the pawn chain intact with the b4 pawn covering c5 — this is why a3 and b4 came first.',
      16: 'Bb2 defends d4 a second time and takes the long diagonal behind the pawn chain.',
      18: 'Bd3 challenges the knight on f5 — trading it removes the one piece holding Black’s blockade together.',
    },
    plans: [
      'Hold d4 with c3, Nf3, Be3 or Bb2 — the whole opening is a fight over one square.',
      'b4 and a4–a5 gains queenside space and denies Black the c5 square permanently.',
      'Trade off Black’s blockading knight on f5 with Bd3; without it the e5 pawn can advance.',
      'Once the queenside is stable, attack with h4, Ng5 and Qg4 against a king that has few defenders.',
      'Keep the light-squared bishop out of the way of ...Ba6 trades; that bishop is Black’s worst piece, so never help it.',
      'If Black wins the d4 pawn, make sure the resulting open lines favour your development — a pawn is a fair price for the initiative here.',
    ],
    watchOut: 'Playing Bd3 before defending d4 enough times drops the centre. In the Advance French, count the attackers and defenders of d4 before every single move.',
  },
  {
    id: 'caro-kann',
    name: 'Caro-Kann, Classical',
    eco: 'B19',
    side: 'b',
    family: 'vs 1.e4',
    moves: [
      'e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4', 'Bf5', 'Ng3', 'Bg6',
      'h4', 'h6', 'Nf3', 'Nd7', 'h5', 'Bh7', 'Bd3', 'Bxd3', 'Qxd3', 'e6',
    ],
    idea: 'Everything the French offers, without trapping the light-squared bishop. Solid, low-risk, structurally sound, and very hard to beat — Black develops the problem piece before closing the pawn chain.',
    notes: {
      1: 'c6 prepares ...d5 with the c-pawn, leaving the c8 bishop its diagonal.',
      7: 'Bf5 — the whole point. The bishop gets out before ...e6 shuts the door.',
      11: 'h6 gives the bishop a retreat and stops h5 trapping it. Necessary, not optional.',
      13: 'Nd7 keeps the option of ...Ngf6 without letting White wreck the structure with Nxf6+.',
      15: 'Bh7 is not a retreat in disgrace: the bishop has done its job and will come back via ...Bxd3 or ...Bg8–f7.',
      17: 'Bxd3 trades Black’s traditionally bad bishop for White’s good one. That alone justifies the whole opening.',
      19: 'e6 finally closes the diagonal — safely, because the bishop is already off the board.',
    },
    plans: [
      'Finish with ...e6, ...Ngf6, ...Bd6 and castle; the structure is sound and needs no heroics.',
      'The ...c5 break frees the position when you are ready.',
      'Aim for an endgame: your pawn structure is healthier than White’s in most lines.',
      'Castle queenside when White has spent moves on h4–h5; the kingside is draughty after those pawn moves.',
      '...Qc7 and ...O-O-O puts the rook opposite the d-pawn and prepares ...c5 with real force.',
      'If White’s knight lands on e5, challenge it with ...Nxe5 or ...Nd7 rather than allowing a permanent outpost.',
    ],
    watchOut: 'After ...Bf5 and ...Bg6, White plays h4-h5 to harass the bishop. If you have not played ...h6 in time, the bishop can end up trapped.',
  },
  {
    id: 'caro-advance',
    name: 'Caro-Kann, Advance (Short System)',
    eco: 'B12',
    side: 'w',
    family: 'vs 1.e4',
    moves: [
      'e4', 'c6', 'd4', 'd5', 'e5', 'Bf5', 'Nf3', 'e6', 'Be2', 'Ne7',
      'O-O', 'h6', 'Nbd2', 'Nd7', 'Nb3', 'Bh7', 'Bd2', 'c5', 'dxc5', 'Nxc5',
    ],
    idea: 'Close the centre against the Caro-Kann and play a slow, safe space game. Nigel Short’s treatment: no early pawn storms, just Be2, O-O, Nbd2–b3 and a long squeeze on the queenside.',
    notes: {
      4: 'e5 takes space and shuts in the bishop — except that in the Caro-Kann, Black gets it out first with ...Bf5.',
      5: 'Bf5 is the difference from the French. White cannot punish it immediately, so White plays around it.',
      8: 'Be2 is the Short System: modest, flexible, and it keeps every option open. The g4 lunge is not needed.',
      12: 'Nbd2 heads for b3, eyeing c5 and d4 — the queenside squares that decide this structure.',
      16: 'Bd2 prepares Bb4 or Ba5 ideas and keeps c1 clear for a rook.',
      17: 'c5 is Black’s freeing break. Meet it in a way that leaves you the better structure, not automatically.',
      19: 'Nxc5 recaptures and leaves a fluid position where White’s extra space on the kingside is the lasting factor.',
    },
    plans: [
      'Be2, O-O and Nbd2–b3 — a sound set-up that needs no memorised theory.',
      'Meet ...c5 with dxc5 or c3, choosing whichever leaves Black with the weaker pawn.',
      'The e5 pawn cramps Black permanently; defend it with Re1 and Bf4 rather than pushing it too early.',
      'a4 and a5 clamps the queenside and gives your knight the b6 square.',
      'Trade off Black’s light-squared bishop if you can — it is unusually good for a Caro-Kann bishop.',
      'Attack on the kingside only once the queenside is frozen; with two weak wings, Black cannot hold both.',
    ],
    watchOut: 'Grabbing space with g4 before castling is the standard way to lose this line. The Short System works because White stays solid — the space advantage does the winning.',
  },
  {
    id: 'scandinavian',
    name: 'Scandinavian Defence',
    eco: 'B01',
    side: 'b',
    family: 'vs 1.e4',
    moves: [
      'e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qa5', 'd4', 'Nf6', 'Nf3', 'c6',
      'Bc4', 'Bf5', 'Bd2', 'e6', 'Qe2', 'Bb4', 'O-O-O', 'Nbd7', 'Kb1', 'O-O-O',
    ],
    idea: 'Strike at the centre on move one and get a clear, easy-to-play structure. Very little theory to memorise and the same set-up against almost anything — ideal while you are learning.',
    notes: {
      3: 'Qxd5 recaptures, accepting that the queen will be chased. The tempo White gains is the price of a simple position.',
      5: 'Qa5 is the main square: safe from immediate attack, eyeing the queenside.',
      9: 'c6 gives the queen a retreat and supports ...d5 ideas later. Quiet, but important.',
      11: 'Bf5 gets the bishop outside the pawn chain before ...e6 — the same principle as the Caro-Kann.',
      15: 'Bb4 pins the knight on c3 and makes the White queenside uncomfortable before Black commits the king.',
      17: 'Nbd7 develops and covers b6 and c5, the squares White’s pieces want.',
      19: 'O-O-O puts the rook opposite the White queen and completes a set-up Black can reach in almost every Scandinavian.',
    },
    plans: [
      'Develop with ...Bf5 or ...Bg4, ...e6, ...Nbd7 and castle — the setup is the same in most lines.',
      'Queenside castling leads to sharp play; kingside castling keeps it simple.',
      'Your structure is symmetrical and sound; play for solidity, not early tricks.',
      'The ...c5 break at the right time gives the queen on a5 a purpose and opens lines toward White’s king.',
      'Trade the light-squared bishops via ...Bg6 and ...Bh5–g6; it takes the sting out of White’s attack.',
      'If both sides castle long, attack with ...b5 and ...b4 only when your king has enough cover.',
    ],
    watchOut: 'Keep track of your queen on a5. Nd2-b3 and Bd2 ideas gain tempo on her, and losing time with the queen is how this opening goes wrong.',
  },
  {
    id: 'pirc',
    name: 'Pirc Defence, Classical',
    eco: 'B08',
    side: 'b',
    family: 'vs 1.e4',
    moves: [
      'e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6', 'Nf3', 'Bg7', 'Be2', 'O-O',
      'O-O', 'c6', 'a4', 'Nbd7', 'h3', 'e5', 'dxe5', 'dxe5', 'a5', 'Qc7',
    ],
    idea: 'Let White take the centre, then chip away at it from a safe, flexible set-up. The bishop on g7 and the ...c6/...e5 pawn break are all the structure Black needs, and there is very little forced theory.',
    notes: {
      1: 'd6 concedes the centre on purpose — a hypermodern choice, not a passive one.',
      5: 'g6 prepares the fianchetto that gives the whole opening its bite.',
      11: 'c6 is the safe, flexible Pirc set-up: it covers b5 and d5 and prepares ...b5 or ...e5.',
      12: 'a4 stops ...b5. It also weakens b4 permanently, which Black can use later.',
      15: 'e5 is the thematic strike: with ...c6 played, Black can hit d4 without loosening anything.',
      17: 'dxe5 leaves a symmetrical structure where the g7 bishop finally has open air on the long diagonal.',
      19: 'Qc7 takes aim at e5 and c-file squares and connects the rooks — a normal, useful move in a normal, healthy position.',
    },
    plans: [
      'The ...e5 or ...c5 break: the Pirc is not about waiting, it is about picking the right moment to hit the centre.',
      'Reroute the knight via ...Nd7–c5 to press e4 and use the hole a4 leaves on b4 or c5.',
      'Keep the g7 bishop — it is the piece that justifies the whole set-up, so avoid trading it for a knight.',
      'Against a kingside pawn storm (f4, g4, h4), break in the centre immediately rather than defending.',
      '...b5 and ...a6 gives queenside play when White castles long.',
      'Meet f4 with ...Nc6 and pressure on d4; overextended centres are what the Pirc is designed to punish.',
    ],
    watchOut: 'Drifting is fatal. If you develop without ever playing ...e5 or ...c5, White simply plays e5 first and the g7 bishop stares at a wall for the rest of the game.',
  },

  /* ---------------- 1.d4 d5 ---------------- */
  {
    id: 'qgd',
    name: 'Queen’s Gambit Declined',
    eco: 'D37',
    side: 'b',
    family: '1.d4 d5',
    moves: [
      'd4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Nf3', 'Be7', 'Bf4', 'O-O',
      'e3', 'c5', 'dxc5', 'Bxc5', 'Qc2', 'Nc6', 'a3', 'Qa5', 'Rd1', 'Be7',
    ],
    idea: 'The most respected answer to 1.d4. Hold the centre with ...d5, develop soundly, and accept a slightly passive but very hard to crack position that has been the backbone of world championship matches for a century.',
    notes: {
      3: 'e6 supports d5. It shuts in the c8 bishop, which is the one real drawback.',
      7: 'Be7 is modest but correct — it unpins and prepares to castle without provoking anything.',
      11: 'c5 is the freeing break. Played at the right moment it solves all of Black’s problems in one go.',
      13: 'Bxc5 recaptures with a developed piece. Black has traded the cramping d-pawn for an active bishop.',
      17: 'Qa5 pins the knight on c3 to the queen on c2 and takes aim at the loose a3 pawn.',
      19: 'Be7 steps back off the exposed diagonal. Retreating a piece that has done its job is not a wasted move.',
    },
    plans: [
      'Free the position with ...c5 or ...dxc4 followed by ...c5 at the right moment.',
      'Solve the c8 bishop: ...b6 and ...Bb7, or ...Nbd7 and ...dxc4 then ...b5.',
      'If White plays for the minority attack with b4-b5, meet it with central play.',
      '...Ne4 is the standard equaliser: it trades a pair of pieces and relieves the cramp.',
      'Take on c4 when White has committed the bishop to d3, gaining a tempo on the recapture.',
      'The half-open c-file after ...c5 and a trade is your main source of activity — put a rook on c8 early.',
    ],
    watchOut: 'Do not take on c4 too early without a follow-up — White simply plays e4 and gets the full centre for free.',
  },
  {
    id: 'qga',
    name: 'Queen’s Gambit Accepted',
    eco: 'D20',
    side: 'b',
    family: '1.d4 d5',
    moves: [
      'd4', 'd5', 'c4', 'dxc4', 'Nf3', 'Nf6', 'e3', 'e6', 'Bxc4', 'c5',
      'O-O', 'a6', 'a4', 'Nc6', 'Qe2', 'cxd4', 'Rd1', 'Be7', 'exd4', 'O-O',
    ],
    idea: 'Take the pawn, give it back, and use the tempi to free the position with ...c5 and ...e6. Black gets the easy piece play the QGD never allows, at the cost of conceding the centre for a few moves.',
    notes: {
      3: 'dxc4 is not a pawn grab — the pawn cannot be held. It is a way to gain time by making White spend a move recapturing.',
      7: 'e6 opens the bishop and prepares ...c5. Playing ...b5 to hang on to the pawn is the classic beginner’s error.',
      9: 'c5 hits d4 at once. Black is trading the extra pawn for the freest position available against 1.d4.',
      11: 'a6 prepares ...b5 to gain queenside space and hit the bishop on c4.',
      12: 'a4 stops ...b5 but hands Black the b4 square for a knight or a bishop.',
      16: 'Rd1 supports the isolated pawn that is about to appear and lines the rook up with Black’s queen.',
      18: 'exd4 leaves White with an isolated queen’s pawn: more active pieces, one long-term weakness.',
    },
    plans: [
      'Blockade the isolated d-pawn with a knight on d5 — in front of it, never beside it.',
      'Trade pieces: every exchange makes the isolated pawn weaker and White’s attack thinner.',
      '...Nb4 and ...Nbd5 uses the square a4 concedes and puts a knight on the best square on the board.',
      '...b6 and ...Bb7 completes development and covers d5 a second time.',
      'Avoid ...h6 or ...g6 weaknesses; the isolated-pawn attack needs a hook, so give it none.',
      'Head for the endgame — an isolated pawn that survives the middlegame usually loses the ending.',
    ],
    watchOut: 'Trying to keep the c4 pawn with ...b5 loses material to a4 and axb5. Give the pawn back and take the development instead.',
  },
  {
    id: 'slav',
    name: 'Slav Defence, Main Line',
    eco: 'D17',
    side: 'b',
    family: '1.d4 d5',
    moves: [
      'd4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'dxc4', 'a4', 'Bf5',
      'e3', 'e6', 'Bxc4', 'Bb4', 'O-O', 'Nbd7', 'Qe2', 'Bg6', 'e4', 'O-O',
    ],
    idea: 'Defend d5 with the c-pawn instead of the e-pawn, keeping the light-squared bishop free. All the solidity of the QGD without the bad bishop, and a genuine fight for the centre.',
    notes: {
      3: 'c6 supports d5 and leaves the c8–h3 diagonal open — the difference from the QGD.',
      7: 'dxc4 grabs the pawn, planning ...b5 to hang on to it.',
      8: 'a4 stops ...b5. It costs White the b4 square, which Black can use later.',
      9: 'Bf5 develops the bishop outside the pawn chain, exactly as intended.',
      13: 'Bb4 uses the square a4 weakened, pins the knight, and prepares to castle immediately.',
      17: 'Bg6 steps out of the way of e4 in advance. Retreating before you are hit saves the tempo you would spend later.',
      18: 'e4 is White’s big moment: the full centre at last. Black must already be ready for it.',
    },
    plans: [
      'The ...c5 break at the right moment frees everything.',
      'Use the b4 square, weakened by a4, for a knight or bishop.',
      'Do not cling to the c4 pawn — it is a tempo-winner, not a permanent gain.',
      '...Bg6 keeps the good bishop alive; trade it only for White’s light-squared bishop, never for a knight.',
      'Meet e4–e5 with ...Nd5, blockading and hitting c3 at once.',
      'Double rooks on the c-file once you have played ...c5 and traded on d4 or c5.',
    ],
    watchOut: 'Playing ...Bf5 before ...dxc4 allows Qb3 hitting b7 and d5 at once. Move order matters here more than in most openings.',
  },
  {
    id: 'semi-slav',
    name: 'Semi-Slav, Meran',
    eco: 'D47',
    side: 'b',
    family: '1.d4 d5',
    moves: [
      'd4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'e6', 'e3', 'Nbd7',
      'Bd3', 'dxc4', 'Bxc4', 'b5', 'Bd3', 'Bb7', 'O-O', 'a6', 'e4', 'c5',
    ],
    idea: 'Support d5 with both ...c6 and ...e6, then take on c4 and expand on the queenside with tempo. The Meran gives Black the most active position available in the Queen’s Gambit — at the cost of a shut-in bishop for a few moves.',
    notes: {
      3: 'c6 and then ...e6 is the Semi-Slav: double protection for d5, and the c8 bishop is temporarily the price.',
      9: 'Nbd7 prepares ...dxc4 followed by ...b5, which is the entire Meran plan in two moves.',
      11: 'dxc4 only now — with the bishop committed to d3, the recapture costs White a tempo.',
      13: 'b5 gains space and drives the bishop back again. Two tempi won in three moves.',
      15: 'Bb7 finally solves the problem bishop. It bears down on e4, the square White most wants.',
      18: 'e4 is White’s central break, and it comes with a threat of e5. Black must hit back at once.',
      19: 'c5 attacks d4 and opens the long diagonal for the bishop on b7. Everything Black has played leads here.',
    },
    plans: [
      '...b5, ...Bb7 and ...c5 — the queenside expansion is the point of the whole opening.',
      'Pressure e4 with ...Bb7 and ...Rc8; White’s big centre is always one tempo from becoming a target.',
      'Meet e5 with ...cxd4 and ...Ng4 or ...Nd5, hitting the overextended pawn immediately.',
      'The half-open c-file is yours: ...Rc8 and ...Qb6 build real pressure on c3 and d4.',
      'Castle when the centre is stable — the king can be left in the middle for a move or two, but never three.',
      'If White takes on b5, the tempo you gain in the centre is worth more than the pawn.',
    ],
    watchOut: 'Taking on c4 before White has committed the bishop just gives away the centre. In the Meran, the move order ...Nbd7 first, ...dxc4 second is not negotiable.',
  },
  {
    id: 'london',
    name: 'London System',
    eco: 'D02',
    side: 'w',
    family: '1.d4',
    moves: [
      'd4', 'd5', 'Bf4', 'Nf6', 'e3', 'e6', 'Nf3', 'Bd6', 'Bg3', 'O-O',
      'Bd3', 'c5', 'c3', 'Nc6', 'Nbd2', 'b6', 'Ne5', 'Bb7', 'f4', 'Ne7',
    ],
    idea: 'A setup rather than a theory battle: the same few moves against almost anything. Solid, quick to learn, and genuinely good — which is why it is everywhere from club level to the world championship.',
    notes: {
      2: 'Bf4 develops the problem bishop outside the pawn chain before playing e3.',
      8: 'Bg3 preserves the bishop when Black offers a trade with ...Bd6.',
      10: 'Bd3 takes the b1–h7 diagonal. Together with Qc2 this is the London’s standard mating battery.',
      12: 'c3 holds d4 so that Ne5 can never be undermined by ...c5xd4.',
      14: 'Nbd2 supports the knight that is about to land on e5 — the outpost only works if it can be recaptured on.',
      16: 'Ne5 is the move the whole system is built around: a protected knight in Black’s half of the board.',
      18: 'f4 cements the knight on e5 for good and starts the kingside attack with Rf3–h3 or Qf3 to follow.',
    },
    plans: [
      'Ne5 supported by f4 and Nd2 is the main attacking idea.',
      'Qe2, O-O-O and a kingside pawn storm in sharper versions.',
      'The c2–h7 diagonal with Bd3 and Qc2 is a standard mating battery.',
      'Rf3–h3 lifts the rook into the attack once the knight on e5 is secure.',
      'If Black trades on e5, recapture with the pawn — the wedge on e5 cramps Black permanently.',
      'When Black plays ...Qb6 hitting b2, answer with Qb3 or Nc4 rather than defending passively with Rb1.',
    ],
    watchOut: 'Playing the moves in autopilot against ...c5 and ...Qb6 hits b2 and can cost a pawn. The system still needs you to look at the board.',
  },
  {
    id: 'catalan',
    name: 'Catalan Opening, Open',
    eco: 'E06',
    side: 'w',
    family: '1.d4',
    moves: [
      'd4', 'Nf6', 'c4', 'e6', 'g3', 'd5', 'Bg2', 'Be7', 'Nf3', 'O-O',
      'O-O', 'dxc4', 'Qc2', 'a6', 'Qxc4', 'b5', 'Qc2', 'Bb7', 'Bd2', 'Be4',
    ],
    idea: 'The Queen’s Gambit with the bishop on g2. That bishop presses down the long diagonal for the entire game — often still doing damage forty moves later, which is why the Catalan is considered one of the most unpleasant openings to face.',
    notes: {
      4: 'g3 prepares the fianchetto. White is happy to give up a pawn on c4 for lasting pressure.',
      11: 'dxc4 grabs the pawn. White usually regains it with Qc2 or Qa4, or plays on for the initiative.',
      12: 'Qc2 recovers the pawn without hurrying — the queen on c2 also supports e4 later.',
      13: 'a6 prepares ...b5 to keep the pawn. Black must spend time on this, which is exactly the Catalan bargain.',
      15: 'b5 gains queenside space, but every pawn move there loosens the squares the g2 bishop already watches.',
      17: 'Bb7 contests the long diagonal, the only way for Black to neutralise the Catalan bishop.',
      19: 'Be4 offers the trade of exactly the piece Black most wants off the board. Whether to allow it is White’s first real decision.',
    },
    plans: [
      'Recover the c4 pawn with Qc2/Qa4 and Ne5, or leave it and play for pressure.',
      'The g2 bishop plus a rook on d1 makes ...c5 and ...b5 hard for Black to achieve.',
      'e4 at the right moment turns the pressure into a space advantage.',
      'a4 cracks the b5 pawn open and leaves Black with a weak c6 or a6 square.',
      'Ne5 and Nd2 covers the long diagonal and supports the e4 break at the same time.',
      'Avoid trading the g2 bishop, even for a rook’s worth of activity — it is the entire opening in one piece.',
    ],
    watchOut: 'Do not chase the c4 pawn at all costs. The compensation is positional, and spending four moves to win it back usually hands Black the freeing break.',
  },

  /* ---------------- Indian defences ---------------- */
  {
    id: 'kid',
    name: 'King’s Indian Defence, Classical',
    eco: 'E92',
    side: 'b',
    family: 'Indian defences',
    moves: [
      'd4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Nf3', 'O-O',
      'Be2', 'e5', 'O-O', 'Nc6', 'd5', 'Ne7', 'Ne1', 'Nd7', 'Be3', 'f5',
    ],
    idea: 'Let White build the big centre, then attack it. Black concedes space for a violent kingside attack — one of the most uncompromising ways to play for a win with the black pieces.',
    notes: {
      3: 'g6 prepares the fianchetto. Black does not contest the centre yet; that comes later.',
      11: 'e5 is the thematic strike. The position usually closes, and then both sides attack on opposite wings.',
      13: 'Nc6 provokes d5, which is exactly what Black wants: a closed centre turns the game into a race.',
      14: 'd5 closes the centre and gains space. From here the game is decided on the wings, not in the middle.',
      15: 'Ne7 reroutes to g6 or f5 — behind the pawn chain, where the knight supports ...f5 and ...f4.',
      17: 'Nd7 clears the f-pawn’s path and eyes c5 and f6. Black needs every piece behind the coming pawn storm.',
      19: 'f5 is the move the whole opening exists for. Everything Black plays from here goes at the White king.',
    },
    plans: [
      'Once the centre closes with d5, play ...f5, ...f4, ...g5, ...h5 and storm the king.',
      'Reroute the f6 knight — ...Ne8 or ...Nd7 — so the f-pawn can advance.',
      'Ignore the queenside. White will get counterplay there; the race is the whole game.',
      '...f4 and ...g5–g4 is the standard pawn-storm order; never trade the f-pawn on e4 without reason.',
      'Get a rook to f6 and swing it to h6 — the attack usually needs a third heavy piece.',
      'If White breaks with c5 and cxd6, recapture in the way that keeps the centre closed, even at the cost of a pawn.',
    ],
    watchOut: 'If you attack slowly, White’s queenside break arrives first and you have nothing. The KID punishes hesitation harder than almost any opening.',
  },
  {
    id: 'nimzo',
    name: 'Nimzo-Indian, Rubinstein',
    eco: 'E48',
    side: 'b',
    family: 'Indian defences',
    moves: [
      'd4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'e3', 'O-O', 'Bd3', 'd5',
      'Nf3', 'c5', 'O-O', 'Nc6', 'a3', 'Bxc3', 'bxc3', 'dxc4', 'Bxc4', 'Qc7',
    ],
    idea: 'Control the centre with pieces instead of pawns. The bishop pins the knight that guards e4, and Black usually trades it at the perfect moment to leave White with doubled, static c-pawns.',
    notes: {
      5: 'Bb4 pins the c3 knight and fights for e4 without committing a pawn.',
      9: 'd5 stakes a central claim now that the pin restrains White.',
      11: 'c5 hits the centre from the other side — pressure from both wings is the Nimzo method.',
      14: 'a3 forces the issue. Black must either trade on c3 or retreat, so the bishop has done its work either way.',
      15: 'Bxc3 is played now precisely because White has spent a tempo on a3 to ask the question.',
      17: 'dxc4 makes White recapture with the bishop, leaving the c-pawns doubled and immobile.',
      19: 'Qc7 eyes c3 and the b8–h2 diagonal, and prepares ...e5 to fix the doubled pawns for good.',
    },
    plans: [
      'Trade on c3 when it doubles White’s pawns and you can blockade the c4 square.',
      'Play against the doubled pawns with ...Na5, ...b6 and ...Ba6.',
      'If White avoids the doubling, you have a comfortable game with easy development.',
      '...e5 followed by ...e4 fixes the c3 pawn and shuts the bishop pair out of the game.',
      'Blockade on the light squares: a knight on c4 or a bishop on a6 is worth more than material here.',
      'Avoid opening the position while White has two bishops — keep the centre half-closed until you have traded one off.',
    ],
    watchOut: 'Do not take on c3 automatically. It gives up the bishop pair; only do it when the structural damage is worth more than the bishop.',
  },
  {
    id: 'queens-indian',
    name: 'Queen’s Indian Defence',
    eco: 'E15',
    side: 'b',
    family: 'Indian defences',
    moves: [
      'd4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6', 'g3', 'Ba6', 'b3', 'Bb4+',
      'Bd2', 'Be7', 'Bg2', 'c6', 'Bc3', 'd5', 'Ne5', 'Nfd7', 'Nxd7', 'Nxd7',
    ],
    idea: 'The Nimzo-Indian’s sister: when White avoids Nc3, Black fights for e4 with the bishop on b7 or a6 instead. Extremely solid, very hard to attack, and rich in small positional battles over one square.',
    notes: {
      5: 'b6 prepares the fianchetto that fights for e4 from a distance.',
      7: 'Ba6 hits c4 directly and makes White spend a move — usually b3 — weakening the long diagonal.',
      9: 'Bb4+ is the tempo move: White must block, and every blocking piece is slightly misplaced.',
      13: 'c6 supports ...d5 and gives the bishop a retreat. Black is building an unbreakable light-squared wall.',
      14: 'Bc3 puts the bishop on the long diagonal behind the knight, aiming at the g7 square and the centre.',
      16: 'Ne5 occupies the outpost. Black must challenge it or be squeezed.',
      17: 'Nfd7 offers the trade at once. Trading White’s best piece is worth a tempo of retreat.',
    },
    plans: [
      '...Ba6 and ...Bb7 both fight for e4 — pick the one that hits whichever piece White has committed.',
      'Play ...d5 and build the light-squared wall; the position is then extremely difficult to break.',
      '...c5 instead of ...c6 gives a sharper game with pressure on d4 — choose by whether White has played e3 or g3.',
      'Trade off a knight that reaches e5; an unchallenged outpost is the only way White gets an edge here.',
      'The ...Ne4 jump is Black’s standard freeing move, gaining space in the centre.',
      'Once equal, play on the c-file — ...Rc8 and ...c5 turn the solid structure into real pressure.',
    ],
    watchOut: 'Playing ...Bb7 and ...d5 without ...c6 or ...c5 leaves a purely passive position. The bishop needs an open diagonal, so always get one of the c-pawn breaks in.',
  },
  {
    id: 'grunfeld',
    name: 'Grünfeld Defence, Exchange',
    eco: 'D85',
    side: 'b',
    family: 'Indian defences',
    moves: [
      'd4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'cxd5', 'Nxd5', 'e4', 'Nxc3',
      'bxc3', 'Bg7', 'Nf3', 'c5', 'Rb1', 'O-O', 'Be2', 'cxd4', 'cxd4', 'Qa5+',
    ],
    idea: 'Invite White to build an imposing pawn centre, then demolish it. A hypermodern opening for players who are comfortable defending accurately in order to win — every black piece is aimed at d4.',
    notes: {
      5: 'd5 in the centre, unlike the King’s Indian — this is the defining difference.',
      9: 'Nxc3 trades off before the knight is kicked, damaging White’s structure.',
      11: 'Bg7 points straight at the big centre White has just built.',
      13: 'c5 hits d4 immediately. In the Grünfeld, the attack on the centre cannot wait.',
      14: 'Rb1 saves the b2 pawn and prepares b4 — White’s standard way of getting the rook into the game.',
      17: 'cxd4 forces the issue and leaves White with an isolated, exposed d-pawn to defend.',
      19: 'Qa5+ picks up a tempo and often the a2 pawn, turning the pressure into something concrete.',
    },
    plans: [
      'Hit d4 with ...c5 immediately; the centre is a target, not an asset for White.',
      'Pressure c3 and c4 with ...Qa5, ...Rc8 and the g7 bishop.',
      'If White’s centre survives and advances, you are worse — timing is everything.',
      '...Bg4 pins the knight that defends d4; removing one defender is usually enough.',
      '...Nc6 and ...Rd8 piles on the d-pawn from both sides.',
      'Trade queens when you can: White’s compensation is dynamic, and it disappears in an endgame.',
    ],
    watchOut: 'Passive play loses quickly. If you do not challenge d4 within a few moves, White’s centre rolls forward and the g7 bishop bites on granite.',
  },
  {
    id: 'benoni',
    name: 'Modern Benoni',
    eco: 'A70',
    side: 'b',
    family: 'Indian defences',
    moves: [
      'd4', 'Nf6', 'c4', 'c5', 'd5', 'e6', 'Nc3', 'exd5', 'cxd5', 'd6',
      'e4', 'g6', 'Nf3', 'Bg7', 'Be2', 'O-O', 'O-O', 'Re8', 'Nd2', 'Na6',
    ],
    idea: 'Accept a permanently worse pawn structure in exchange for the half-open e-file, a queenside majority and the most dangerous bishop on g7 in any opening. A fighting choice: Black is either much better or simply worse.',
    notes: {
      3: 'c5 challenges d4 at once and invites White to push past, which is exactly what Black wants.',
      5: 'e6 undermines the d5 pawn so that Black gets the half-open e-file after the trade.',
      9: 'd6 and ...g6 is the Benoni set-up: a pawn chain pointing at the queenside, a fianchetto pointing at it too.',
      13: 'Bg7 aims at the long diagonal and at b2 — the Benoni bishop is the best piece on the board.',
      17: 'Re8 puts the rook on the half-open file behind the e4 pawn, which is White’s main weakness.',
      18: 'Nd2 heads for c4 to hit d6 — White’s standard plan of attacking the backward pawn.',
      19: 'Na6 is the modern square: the knight goes to c7 or b4 and supports the ...b5 break.',
    },
    plans: [
      '...b5 is the break that gives the queenside majority meaning — prepare it with ...a6, ...Rb8 or ...Na6–c7.',
      'Pressure e4 with ...Re8, ...Bg4 and ...Nbd7–e5.',
      'Keep the g7 bishop at all costs; the entire position depends on the long diagonal.',
      'Meet e4–e5 with ...dxe5 and ...Ng4 or ...Re8 — an advanced pawn there is a weakness, not a threat.',
      'Watch the d6 pawn: defend it with ...Qc7 or ...Ne5 rather than tying a rook to it forever.',
      'If White plays f4 and e5, hit back immediately — the Benoni loses only when Black is passive.',
    ],
    watchOut: 'The d6 pawn and the e-file cut both ways. If White gets Nc4, Bf4 and e5 in before your ...b5 break, the position collapses very quickly.',
  },

  /* ---------------- Flank openings ---------------- */
  {
    id: 'english',
    name: 'English Opening, Four Knights',
    eco: 'A29',
    side: 'w',
    family: 'Flank openings',
    moves: [
      'c4', 'e5', 'Nc3', 'Nf6', 'Nf3', 'Nc6', 'g3', 'Bb4', 'Bg2', 'O-O',
      'O-O', 'Re8', 'Nd5', 'Bf8', 'd3', 'h6', 'a3', 'd6', 'Rb1', 'a5',
    ],
    idea: 'A Sicilian with colours reversed and an extra tempo. Flexible, low-theory, and it can transpose into almost anything — White plays a known structure a move up, which is worth more than it sounds.',
    notes: {
      0: 'c4 controls d5 without committing a centre pawn — the flank approach.',
      6: 'g3 and Bg2 is the main setup: the bishop fights for d5 from a distance.',
      12: 'Nd5 takes the outpost the whole opening has been about, with tempo on the bishop.',
      13: 'Bf8 retreats rather than trading — Black keeps the bishop pair and waits.',
      14: 'd3 supports e4 later and opens the c1 bishop. In the English, the pawns stay low and the pieces do the work.',
      16: 'a3 prepares b4, gaining space on the side where White’s pawns already point.',
      18: 'Rb1 backs up the b4 push. The rook is doing real work on a closed file because that file is about to open.',
    },
    plans: [
      'Play for d5 or the b4-b5 queenside expansion.',
      'Rb1 and b4 is the standard space-gaining plan on the queenside.',
      'Be ready to transpose into 1.d4 structures if Black plays ...d5.',
      'The g2 bishop plus Nd5 fights for the one central square that matters — never trade the bishop cheaply.',
      'If Black attacks on the kingside, break in the centre with d4 or e3 and d4 at once.',
      'Trade on b4 or c5 only when it opens a file your rook already sits on.',
    ],
    watchOut: 'Flexibility is not a plan. If you shuffle without committing to a break, Black takes the centre and you end up worse from a "safe" opening.',
  },
  {
    id: 'reti',
    name: 'Réti Opening, Double Fianchetto',
    eco: 'A09',
    side: 'w',
    family: 'Flank openings',
    moves: [
      'Nf3', 'd5', 'c4', 'e6', 'g3', 'Nf6', 'Bg2', 'Be7', 'O-O', 'O-O',
      'b3', 'c5', 'Bb2', 'Nc6', 'e3', 'b6', 'd3', 'Bb7', 'Nbd2', 'Qc7',
    ],
    idea: 'Control the centre entirely with pieces. Both bishops on long diagonals, no committal pawn moves, and White keeps every transposition available — into a Catalan, an English or a Queen’s Gambit as Black commits.',
    notes: {
      0: 'Nf3 commits to nothing. The Réti’s strength is that Black must show their hand first.',
      2: 'c4 hits d5 from the flank. Black must decide between ...d4, ...dxc4 and holding the centre.',
      10: 'b3 prepares the second fianchetto. Two bishops on long diagonals is the whole set-up.',
      14: 'e3 gives the dark-squared bishop and the knight a stable centre without blocking anything.',
      16: 'd3 keeps the centre low and flexible; the pawn break e4 or d4 comes only when it is clearly good.',
      18: 'Nbd2 completes development and prepares e4 — the break this whole system is aiming for.',
    },
    plans: [
      'Fight for e4: Nbd2, Qe2 and Re1, then push when Black cannot meet it.',
      'Both bishops on long diagonals — never block them with your own pawns.',
      'Take on d5 to open the g2 bishop’s diagonal when Black cannot recapture comfortably.',
      'Play against a hanging-pawn or isolated-pawn centre with pressure rather than blockade.',
      'Transpose deliberately: if Black plays ...d5 and ...e6, d4 turns this into a Catalan you already understand.',
      'A rook on c1 opposite Black’s queen makes ...c5 awkward and often wins a tempo.',
    ],
    watchOut: 'Playing the set-up on autopilot without ever pushing e4 or d4 hands Black a free centre. The Réti wins the centre later, but it does have to win it.',
  },
];

export const FAMILIES = [...new Set(OPENINGS.map((o) => o.family))];

export function getOpening(id: string): Opening | undefined {
  return OPENINGS.find((o) => o.id === id);
}
