# specify base image from dockerhub
FROM node:20-alpine

LABEL version="1.0"
LABEL description="React Frontend for the Library API"

WORKDIR /app

COPY ["package.json","package-lock.json*","./"]

# Install dependencies and clear npm cache
RUN npm install && npm cache clean --force

COPY . .

CMD [ "npm", "run", "start" ]